# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory
WORKDIR /app

# Copy requirements.txt
COPY app/backend/requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY app/backend/ ./

# Expose port 8000
EXPOSE 8000

# Run the application
CMD ["python", "app.py"]
